# prefix
unbind C-b
set -g prefix C-s
bind C-s send-prefix

# split panes using | and -
unbind %
unbind '"'
bind | split-window -h
bind - split-window -v

# move hjkl
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# reload
unbind r
bind r source-file $HOME/.config/tmux/tmux.conf

# escape timeout
set -sg escape-time 0

# mouse
set -g mouse on

# clipboard
set -g set-clipboard on

# nvim colours
# set-option -ga terminal-overrides ",xterm-256color:Tc"
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:RGB"

# numbering
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# vi copy
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi S-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
